#!/usr/bin/env bash
#
# Copyright (C) 2018 Abhishek AN (DarkAbhi)
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Color Code & Formatting 
bold=$(tput bold)
normal=$(tput sgr0)
black='\e[0;30m'        # Black
red='\e[0;31m'          # Red
green='\e[0;32m'        # Green
yellow='\e[0;33m'       # Yellow
blue='\e[0;34m'         # Blue
purple='\e[0;35m'       # Purple
cyan='\e[0;36m'         # Cyan
white='\e[0;37m'        # White
lmagenta='\e[95m'
nocol='\033[0m'         # Default

###############
#			  #
#  VARIABLES  #
#             #
###############

COUNT=$(nproc --all)
THREADS="$((COUNT * 2))"
KERNEL_DIR=$PWD
CCACHE="$(command -v ccache)"
IMAGE=$KERNEL_DIR/out/arch/arm64/boot/Image.gz-dtb
ANYKERNEL_DIR=/home/$USER/AnyKernel2/asus
EXPORT_DIR=/home/$USER/flashablezips/asus/
FINAL_IMAGE=zImage
BASE_VER="RawWork"
KERNEL_VER=1.2
FINAL_ZIP=$BASE_VER-v$KERNEL_VER.zip
BUILD_NUMBER=$(date +%H%M%S)
file=$PWD/build-kernel

function help_menu() {
    echo
    echo "${bold}OVERVIEW:${normal} Build a gcc toolchain"
    echo
    echo "${bold}USAGE:${normal} ${0} <options>"
    echo
    echo "${bold}EXAMPLE:${normal} ${0} -a arm64 -s linaro -v 7"
    echo
    echo "${bold}REQUIRED PARAMETERS:${normal}"
    echo "  -a      | --arch:        		  Possible values: arm, arm64. This is the target architecture. Defaults to arm64."
    echo "  -gt     | --gcc-toolchain 		  Possible values: aosp(i.e GCC 4.9), 7,8 or 9."
    echo "  -ct     | --clang-toolchain 	  Possible values: 8 or 9."
    echo "  -d      | --defconfig:			  Input defconfig to be used for building. Defaults to rawwork_defconfig."
    echo "  -gt-32  | --gcc-32-bit-toolchain  Possible values: aosp(i.e GCC 4.9), 7,8 or 9."
    echo "  -c      | --clang			 	  Builds with clang."
    echo
}

# Parse parameters
function parse_parameters() {
    while [[ ${#} -ge 1 ]]; do
        case "${1}" in
            # REQUIRED FLAGS
            "-a"|"--arch") shift && ARCH=${1} ;;
            "-gt"|"--gcc-toolchain") shift && GCC_TOOLCHAIN=${1} ;;
            "-ct"|"--clang-toolchain") shift && CLANG_TOOLCHAIN=${1} ;;
			"-d"|"--defconfig") shift && DEFCONFIG=${1} ;;
			"-gt-32"|"--gcc-32-bit-toolchain") shift && GCC_32_BIT_TOOLCHAIN=${1} ;;
			"-c"|"--clang") shift && CLANG=true ;;

            # HELP!
            "-h"|"--help") help_menu; exit ;;
        esac

        shift
done
}

function assign_values() {

################
#			   #
#   DEFAULTS   #
#              #
################

#[[ -z ${ARCH} ]] && ARCH=arm64

[[ -z ${DEFCONFIG} ]] && DEFCONFIG="rawwork_defconfig"

MAKE="make -j${THREADS} O=out ARCH=${ARCH}"

if [[ -z ${GCC_TOOLCHAIN} ]]; then
	echo
	echo -e "$blue${bold}****************************************************************"
	echo "${bold}GCC TOOLCHAIN NOT SPECIFIED USING AOSP aarch64-linux-android-4.9${normal}"
	echo -e "$blue${bold}****************************************************************$nocol"
	export CROSS_COMPILE=$HOME/toolchains/GCC/aosp-gcc/bin/aarch64-linux-android-
fi

# CHECK IF CLANG IS TO BE USED
if [[ "${CLANG}" == "true" ]]; then
	echo
	echo -e "$lmagenta${bold}***********************************"
	echo "	USING clang version 9.0.3 ${normal}"
	echo -e "$lmagenta${bold}***********************************$nocol"
	export CLANG_TRIPLE="aarch64-linux-gnu-"
	export CC="$HOME/toolchains/CLANG/clang-9/bin/clang"
	KBUILD_COMPILER_STRING=$(${CC} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
fi

# ASSIGN TOOLCHAIN PATH AFTER SPECIFYING
if [[ "${GCC_TOOLCHAIN}" == "aosp" ]]; then
	echo
	echo -e "$green${bold}GCC version: aarch64-linux-android-gcc (GCC) 4.9.x 201.2123 (prerelease)$normal"
	echo
	export CROSS_COMPILE=$HOME/toolchains/GCC/aosp-gcc/bin/aarch64-linux-android-
elif [[ "${GCC_TOOLCHAIN}" == 7 ]]; then
	echo
	echo -e "$green${bold}GCC version: aarch64-linux-gnu-gcc (GCC) 7.4.1 201.2014$normal"
	echo
	export CROSS_COMPILE=$HOME/toolchains/GCC/gcc-7/bin/aarch64-linux-gnu-
	export CROSS_COMPILE_ARM32=$HOME/toolchains/GCC/gcc-7-arm/bin/arm-linux-gnueabi-
	export STRIP=$HOME/toolchains/GCC/gcc-7/bin/arm-linux-gnueabi-strip
fi
}

function clean() {
if [ -d out ]; then
echo -e "$red${bold}*****************************************************"
echo "        Removing out Directory & Creating out          "
echo -e "*****************************************************${normal}$nocol"
#rm -rf out && mkdir out
fi

if [ -e "$ANYKERNEL_DIR/zImage" ]; then
	rm -rf $ANYKERNEL_DIR/$FINAL_IMAGE
fi
}

function notifybuild() {
	curl -s -X POST https://api.telegram.org/bot${BOT_API_KEY}/sendMessage -d text=" Kernel: <code>RawWork Kernel</code>
	Device: <code>Asus Zenfone Max Pro M1</code>
	Branch: <code>$(git rev-parse --abbrev-ref HEAD)</code>
	Build Number: <code>r${BUILD_NUMBER}</code>
	Latest Commit: <code>$(git log --pretty=format:'%h : %s' -1)</code>
	<i>Build started on Arch Macine...</i>" -d chat_id=${CI_CHANNEL_ID} -d parse_mode=HTML
}

function build() {
export CCACHE KBUILD_COMPILER_STRING THREADS ARCH

echo -e "$cyan${bold}***********************************************"
echo "          	Compiling KERNEL!!        "
echo -e "***********************************************${normal}$nocol"

$MAKE $DEFCONFIG
$MAKE
}

function results() {
# Error out if Image.gz-dtb not found
if ! [ -a $IMAGE ];
then
	echo
	echo -e "$red${bold} Kernel Compilation failed! Fix the errors! $nocol"
	echo
	echo -e "$yellow${bold}Build completed in $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds.${normal}$nocol"
	exit 1
else
	echo -e "$green${bold}***********************************************"
	echo "          Copying Image.gz--dtb        "
	echo -e "***********************************************${normal}$nocol"
	mv $IMAGE $ANYKERNEL_DIR/$FINAL_IMAGE
fi

echo -e "$purple${bold}***********************************************"
echo "          Making Flashable Zip        "
echo -e "***********************************************${normal}$nocol"

cd $ANYKERNEL_DIR
zip -r9 $FINAL_ZIP *

echo -e "$green${bold}***********************************************"
echo "          Copying Final ZIP - $FINAL_ZIP to flashable files folder        "
echo -e "***********************************************${normal}$nocol"

mv $FINAL_ZIP $EXPORT_DIR

if [ -e "$ANYKERNEL_DIR/zImage" ]; then
	echo -e "$green***********************************************"
	echo "		zImage exists    "
	next_kernel_version=$(echo "$KERNEL_VER + 0.1" | bc -l)
	sed -i "s/$KERNEL_VER/$next_kernel_version/g" "$file"
	echo -e "$green***********************************************"
	echo "Next Big Kernel Version Will Be${bold} $next_kernel_version${normal}"
fi
}

function upload_finalzip(){
cd $EXPORT_DIR
if [ -a $FINAL_ZIP ]; then
	curl -s -X POST https://api.telegram.org/bot${BOT_API_KEY}/sendMessage -d text="Build compiled successfully in $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds!" -d chat_id=${CI_CHANNEL_ID} -d parse_mode=HTML
	#curl -F chat_id="${CI_CHANNEL_ID}" -F document=@"$(pwd)/${FINAL_ZIP}" https://api.telegram.org/bot${BOT_API_KEY}/sendDocument
else
	echo "Final Kernel Zip: $FINAL_ZIP NOT FOUND"
	curl -s -X POST https://api.telegram.org/bot${BOT_API_KEY}/sendMessage -d text="Build throwing errors. FIX THEM NOOB!" -d chat_id=${CI_CHANNEL_ID}
fi
}

notifybuild
parse_parameters "${@}"
assign_values
clean
START=$(date +%s)
build
BUILD_END=$(date +"%s")
DIFF=$(($BUILD_END - $START))
results
upload_finalzip
echo -e "$yellow${bold}Build completed in $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds.${normal}$nocol"

# END OF SCRIPT
